language: cpp
compiler: gcc
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake .
  - cmake --build .
  - cmake --build . --target package
